name: null
favicon: null
layout_spectrum: 0.13775
typography_spectrum: 0.23424
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f2f2f2'
    - '#e5e5e3'
    - '#acb1ad'
    - '#cececc'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
