name: null
favicon: null
layout_spectrum: 0.38615
typography_spectrum: 0.59485
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a1114'
    - '#1a3036'
    - '#506062'
    - '#919386'
    - '#b0ae9c'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
